"""Generate the UFO's features.fea from structured app data.

Only GSUB that the app models directly is written here (alternates and
ligatures). mark / mkmk / kern / GDEF are left to ufo2ft's feature writers,
which build them from anchors, kerning and ``public.openTypeCategories``.
Anything hand-written lives in the ``customFeatures`` lib key and is appended.
"""

from __future__ import annotations

from collections import defaultdict

LIB = "com.fonttastic"
LIGATURES_KEY = f"{LIB}.ligatures"
CUSTOM_FEA_KEY = f"{LIB}.customFeatures"

HEADER = """\
# Generated by Font-tastic — edit in the app, not here.
languagesystem DFLT dflt;
languagesystem hebr dflt;
"""


def build_features(font, alternates: dict[str, list[tuple[str, str]]]) -> str:
    """``alternates`` maps feature tag -> [(base glyph, alternate glyph), ...]."""
    parts = [HEADER]

    for tag in sorted(alternates):
        by_base = defaultdict(list)
        for base, alt in alternates[tag]:
            if base in font and alt in font:
                by_base[base].append(alt)
        if not by_base:
            continue
        lines = []
        for base in sorted(by_base):
            alts = sorted(by_base[base])
            if len(alts) == 1:
                lines.append(f"    sub {base} by {alts[0]};")
            else:
                lines.append(f"    sub {base} from [{' '.join(alts)}];")
        parts.append(f"feature {tag} {{\n" + "\n".join(lines) + f"\n}} {tag};\n")

    by_feature = defaultdict(list)
    for lig in font.lib.get(LIGATURES_KEY, []):
        comps, out = lig["components"], lig["glyph"]
        if out in font and len(comps) >= 2 and all(c in font for c in comps):
            by_feature[lig.get("feature", "liga")].append((comps, out))
    for tag in sorted(by_feature):
        # longest sequences first so they win over their own prefixes
        rules = sorted(by_feature[tag], key=lambda r: -len(r[0]))
        lines = [f"    sub {' '.join(c)} by {o};" for c, o in rules]
        parts.append(f"feature {tag} {{\n" + "\n".join(lines) + f"\n}} {tag};\n")

    custom = font.lib.get(CUSTOM_FEA_KEY, "").strip()
    if custom:
        parts.append("# --- custom ---\n" + custom + "\n")
    return "\n".join(parts)
